Release export ICON 2024.10 based on tag tags/icon-2024.10.

diff --git a/externals/yac/examples/toy_multi/toy_multi.sh.in b/externals/yac/examples/toy_multi/toy_multi.sh.in
--- a/externals/yac/examples/toy_multi/toy_multi.sh.in
+++ b/externals/yac/examples/toy_multi/toy_multi.sh.in
@@ -1,14 +1,28 @@
 #!@SHELL@
 
+# Copyright (c) 2024 The YAC Authors
+#
+# SPDX-License-Identifier: CC0-1.0
+
+@ENABLE_MCI_FALSE@exit 77
+@ENABLE_UTILS_FALSE@exit 77
+@HAVE_NETCDF_FALSE@exit 77
 @TEST_MPI_FALSE@exit 77
 
-BUILDPATH=(@abs_top_builddir@/python/build/lib.*/)
-PYTHONPATH="${BUILDPATH[0]}:$PYTHONPATH"
-export PYTHONPATH;
-
-@TEST_MPI_TRUE@@MPI_LAUNCH@ \
+cmd="@MPI_LAUNCH@ \
   -n 2 ./toy_multi_reg2d.x : \
-  -n 3 ./toy_multi_unstruct.x : \
-  -n 3 ./toy_multi_unstruct_2.x : \
-  -n 6 ./toy_multi_cube.x \
-@TEST_PYTHON_BINDINGS_TRUE@ : -n 2 @PYTHON@ @abs_srcdir@/toy_multi_curve2d.py
+  -n 3 ./toy_multi_unstruct.x -g '@abs_top_builddir@/grids/icon_grid_0043_R02B04_G.nc' : \
+  -n 3 ./toy_multi_unstruct_2.x -g '@top_srcdir@/grids/GR30_lsm.nc' : \
+  -n 6 ./toy_multi_cube.x"
+
+if test -z '@ENABLE_PYTHON_BINDINGS_TRUE@'; then
+  if @PYTHON@ -c 'import mpi4py' >/dev/null 2>&1; then
+    PYTHONPATH="@abs_top_builddir@/python:$PYTHONPATH"
+    export PYTHONPATH
+    cmd="$cmd :   -n 2 @PYTHON@ '@srcdir@/toy_multi_curve2d.py'"
+  else
+    echo 'WARNING: Python extension is not run due to missing modules' >&2
+  fi
+fi
+
+eval "$cmd"
